/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ModeloTabela;
import Models.TabelaModelo2;
//import Controller.VendasController;
import Controller.vendaProdutosController;
import Models.DAO;
import Models.Venda;
import Models.VendaCarrinho;
import Models.VendaProdutos;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author 03758479100
 */
public class TelaVendas extends javax.swing.JInternalFrame {

    String a = "", b = "", c = "", d = "", e = "", f = "", tp = "0", g = "", h = "";
    String sql = "select * from produtos inner join Lote on idprodutos = FKprodutos";
    ArrayList<Venda> vendas = new ArrayList<>();
    ArrayList<VendaProdutos> vendaProdutos = new ArrayList<>();
    ArrayList vendas2 = new ArrayList();
    boolean txt;
    String text;
    ArrayList dadosVendas = new ArrayList();
    double x = 0, z, vl, vl2, icms1, icms, iss1, iss2, ipi1, ipi2;

    /**
     * Creates new form TelaOrdemServico
     */
    public TelaVendas() {
        initComponents();

        VerificarCodigo();
        DAO dao = new DAO();
        tipoPagamento();

        // preencherTabela(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbloCodVenda = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable29 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisaProdutoVenda = new javax.swing.JTextField();
        btnPesquisa1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPesqusiaTipoVenda = new javax.swing.JTextField();
        btnPesquisa2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtQtdVenda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblValorParcial = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        lbl9 = new javax.swing.JLabel();
        lblIdproduto = new javax.swing.JLabel();
        lblIdlote = new javax.swing.JLabel();
        txtDescontoVenda = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        panelTipoPag = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        cbD = new javax.swing.JCheckBox();
        cbCC = new javax.swing.JCheckBox();
        cbCD = new javax.swing.JCheckBox();
        lblValorTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblIpi = new javax.swing.JLabel();
        lblIcms = new javax.swing.JLabel();
        lblIss = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoVendedor = new javax.swing.JTextField();
        btnFinalizarVenda = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        txtDescontoVendaServico = new javax.swing.JComboBox<>();
        cA = new javax.swing.JLabel();
        cB = new javax.swing.JLabel();
        cC = new javax.swing.JLabel();
        cD = new javax.swing.JLabel();
        cE = new javax.swing.JLabel();
        cF = new javax.swing.JLabel();

        setClosable(true);
        setTitle("VENDAS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda_Tela.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nº :");

        lbloCodVenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jTable29.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable29MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable29);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Nome do produto:");

        btnPesquisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisa1.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisa1.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisa1.setPreferredSize(new java.awt.Dimension(30, 30));
        btnPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Tipo de Produto :");

        btnPesquisa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisa2.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisa2.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisa2.setPreferredSize(new java.awt.Dimension(30, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Quantidade :");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Desconto:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Valor :");

        lblValorParcial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addVenda.png"))); // NOI18N
        btnAddProduto.setMaximumSize(new java.awt.Dimension(50, 50));
        btnAddProduto.setMinimumSize(new java.awt.Dimension(50, 50));
        btnAddProduto.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        txtDescontoVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesqusiaTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel13)
                                        .addGap(11, 11, 11)
                                        .addComponent(txtDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblIdlote)
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calcular))
                                    .addComponent(lblIdproduto))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calcular))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtPesquisaProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPesqusiaTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(btnPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(txtDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorParcial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdproduto)
                            .addComponent(lblIdlote))))
                .addGap(38, 38, 38)
                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Desconto:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Valor Total:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estornoVenda.png"))); // NOI18N
        btnCancelar.setText("Remover Item");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Tipo de Pagamento:");

        panelTipoPag.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Dinheiro:");

        txtDinheiro.setEnabled(false);
        txtDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Troco :");

        txtTroco.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Cartão :");

        txtCartao.setEnabled(false);

        javax.swing.GroupLayout panelTipoPagLayout = new javax.swing.GroupLayout(panelTipoPag);
        panelTipoPag.setLayout(panelTipoPagLayout);
        panelTipoPagLayout.setHorizontalGroup(
            panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTipoPagLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTipoPagLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCartao))
                    .addGroup(panelTipoPagLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTroco)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        panelTipoPagLayout.setVerticalGroup(
            panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTipoPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbD.setText("Dinheiro");
        cbD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDMouseClicked(evt);
            }
        });

        cbCC.setText("Cartão de Crédito");
        cbCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCCMouseClicked(evt);
            }
        });

        cbCD.setText("Cartão de Débito");
        cbCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCDMouseClicked(evt);
            }
        });

        lblValorTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Impostos"));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("ICMS :");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("ISS :");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("IPI :");

        lblIpi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblIcms.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblIss.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIpi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIss, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(lblIss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(lblIpi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Código do Vendedor :");

        btnFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/finalizarCompra.png"))); // NOI18N
        btnFinalizarVenda.setText("Finalizar");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        txtDescontoVendaServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%" }));
        txtDescontoVendaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoVendaServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbloCodVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbD)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(cbCC)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(cbCD))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(btnFinalizarVenda)
                                                            .addGap(140, 140, 140))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel17)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnCancelar))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtDescontoVendaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel18))
                                            .addGap(222, 222, 222)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl8)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(cA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtDescontoVendaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbD)
                                    .addComponent(cbCC)
                                    .addComponent(cbCD))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnFinalizarVenda))
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbloCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl1)
                                    .addComponent(lbl2)
                                    .addComponent(lbl3)
                                    .addComponent(lbl4)
                                    .addComponent(lbl5)
                                    .addComponent(lbl6)
                                    .addComponent(lbl7)
                                    .addComponent(lbl8))
                                .addGap(2, 2, 2)
                                .addComponent(cB, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cA, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cC, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cD, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cE, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cF, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa1ActionPerformed
        sql = "select * from produtos inner join Lote on idprodutos = FKprodutos where nomeProduto like '%" + txtPesquisaProdutoVenda.getText() + "%'";
        preencherTabela(sql);


    }//GEN-LAST:event_btnPesquisa1ActionPerformed

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        vendaProdutosController vd = new vendaProdutosController();
        String aux = "";

        if (txtDescontoVenda.getSelectedItem() == "0%") {
            aux = "0";
        }
        if (txtDescontoVenda.getSelectedItem() == "5%") {
            aux = "5";
        }
        if (txtDescontoVenda.getSelectedItem() == "10%") {
            aux = "10";
        }
        if (txtDescontoVenda.getSelectedItem() == "15%") {
            aux = "15";
        }
        if (txtDescontoVenda.getSelectedItem() == "20%") {
            aux = "20";
        }
        if (txtDescontoVenda.getSelectedItem() == "25%") {
            aux = "25";
        }

        boolean vf = verificarQtd(cF.getText(),h);
        if (vf) {

            PT2(cA.getText(), txtQtdVenda.getText(), aux, cB.getText(), lblValorParcial.getText(), cC.getText(), cD.getText(), cE.getText(), h);
            vendas.add(vd.preencherArray3(cA.getText(), txtQtdVenda.getText(), aux, cB.getText(), lblValorParcial.getText(), cC.getText(), cD.getText(), cE.getText(), h));
            vendaProdutos.add(vd.preencherCarrinho(h, txtQtdVenda.getText(), aux, lblValorParcial.getText(), lbloCodVenda.getText()));
            Limpar1();
        } else {

        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int linhaSelecionada = jTable2.getSelectedRow();
        cA.setText(jTable2.getValueAt(linhaSelecionada, 0).toString());
        cB.setText(jTable2.getValueAt(linhaSelecionada, 4).toString());
        cC.setText(jTable2.getValueAt(linhaSelecionada, 5).toString());
        cD.setText(jTable2.getValueAt(linhaSelecionada, 6).toString());
        cE.setText(jTable2.getValueAt(linhaSelecionada, 7).toString());
        cF.setText(jTable2.getValueAt(linhaSelecionada, 10).toString());
        h = (jTable2.getValueAt(linhaSelecionada, 11).toString());

    }//GEN-LAST:event_jTable2MouseClicked

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        String aux = "";

        if (txtDescontoVenda.getSelectedItem() == "0%") {
            aux = "0";
        }
        if (txtDescontoVenda.getSelectedItem() == "5%") {
            aux = "5";
        }
        if (txtDescontoVenda.getSelectedItem() == "10%") {
            aux = "10";
        }
        if (txtDescontoVenda.getSelectedItem() == "15%") {
            aux = "15";
        }
        if (txtDescontoVenda.getSelectedItem() == "20%") {
            aux = "20";
        }
        if (txtDescontoVenda.getSelectedItem() == "25%") {
            aux = "25";
        }

        lblValorParcial.setText(calcular(cB.getText(), txtQtdVenda.getText(), aux));

        btnAddProduto.grabFocus();

    }//GEN-LAST:event_calcularActionPerformed

    private void jTable29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable29MouseClicked
        int linhaSelecionada = jTable29.getSelectedRow();
        lbl1.setText(jTable29.getValueAt(linhaSelecionada, 0).toString());
        lbl2.setText(jTable29.getValueAt(linhaSelecionada, 1).toString());
        lbl3.setText(jTable29.getValueAt(linhaSelecionada, 2).toString());
        lbl4.setText(jTable29.getValueAt(linhaSelecionada, 3).toString());
        lbl5.setText(jTable29.getValueAt(linhaSelecionada, 4).toString());
        lbl9.setText(jTable29.getValueAt(linhaSelecionada, 8).toString());


    }//GEN-LAST:event_jTable29MouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        x = 0;
        z = x;
        vl2 = 0;
        //z = z - (z * vl2 / 100);
        icms = 0;
        icms1 = icms;
        iss1 = 0;
        iss2 = iss1;
        ipi1 = 0;
        ipi2 = ipi1;
        lblValorTotal.setText("");
        lblIcms.setText("");
        lblIss.setText("");
        lblIpi.setText("");
        cbD.setSelected(false);
        cbCC.setSelected(false);
        cbCD.setSelected(false);
        txtDinheiro.setText("");
        txtCartao.setText("");
        txtTroco.setText("");

        if (!lbl1.getText().equals("")) {
            //remove do arraylist pessoas os dados da linha selecionada.

            int x = vendas.size();
            for (int i = 0; i < vendas.size(); i++) {
                if (vendas.get(i).getA().equals(lbl1.getText())) {
                    vendas.remove(i);
                    vendaProdutos.remove(i);
                    lbl1.setText("");
                }
            }

            //esvazia o arraylist dadosPessoa e, conseguentemente, esvazia a jTable.
            LTB2();
            //preenche a jTable com os dados restantes do arraylist pessoas.

            for (int i = 0; i < vendas.size(); i++) {
                PT2(vendas.get(i).getA(), vendas.get(i).getB(), vendas.get(i).getC(), vendas.get(i).getD(), vendas.get(i).getE(),
                        vendas.get(i).getF(), vendas.get(i).getG(), vendas.get(i).getH(), vendas.get(i).getJ());
            }

        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        String aux = "", dinheiro = "", cartao = "", troco = "";

        if (txtDescontoVendaServico.getSelectedItem() == "0%") {
            aux = "0";
        }
        if (txtDescontoVendaServico.getSelectedItem() == "5%") {
            aux = "5";
        }
        if (txtDescontoVendaServico.getSelectedItem() == "10%") {
            aux = "10";
        }
        if (txtDescontoVendaServico.getSelectedItem() == "15%") {
            aux = "15";
        }
        if (txtDescontoVendaServico.getSelectedItem() == "20%") {
            aux = "20";
        }
        if (txtDescontoVendaServico.getSelectedItem() == "25%") {
            aux = "25";
        }
        vendaProdutosController vndP = new vendaProdutosController();
        DAO dao = new DAO();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date agr = new Date();
        String codvend = dao.buscarFuncionario(txtCodigoVendedor.getText());

        int ic = lblIcms.getText().length();
        int is = lblIss.getText().length();
        int ip = lblIpi.getText().length();
        int vlt = lblValorTotal.getText().length();
        int din = txtDinheiro.getText().length();
        int car = txtCartao.getText().length();
        int tro = txtTroco.getText().length();

        if (din > 0) {
            dinheiro = txtDinheiro.getText().substring(2, din).replace(",", ".");
        } else {
            dinheiro = "0";
        }
        if (car > 0) {
            cartao = txtCartao.getText().substring(2, car).replace(",", ".");
        } else {
            cartao = "0";
        }
        if (din > 0) {
            troco = txtTroco.getText().substring(2, tro).replace(",", ".");
        } else {
            troco = "0";
        }

        String icms = lblIcms.getText().substring(2, ic).replace(",", ".");
        String iss = lblIss.getText().substring(2, is).replace(",", ".");
        String ipi = lblIpi.getText().substring(2, ip).replace(",", ".");
        String valorT = lblValorTotal.getText().substring(2, vlt).replace(",", ".");

        if (codvend.equals(null)) {
            JOptionPane.showMessageDialog(null, "insira um codigo valido");

        } else {
            tipoPagamento();

            vndP.salvarVenda(aux, tp, df.format(agr), "", "0", icms, iss,
                    ipi, codvend, lbloCodVenda.getText(), txtCodigoVendedor.getText(), valorT, dinheiro,
                    cartao, troco);

            for (int i = 0; i < vendaProdutos.size(); i++) {
                vndP.salvarLoteVenda(vendaProdutos.get(i).getFkLoteVendas(), vendaProdutos.get(i).getQtd(), vendaProdutos.get(i).getDescontoItemVendProduto(),
                        vendaProdutos.get(i).getValorParcialVendProduto(),
                        lbloCodVenda.getText(), "venda");
            }

        }
        vendas.removeAll(vendas);
        vendaProdutos.removeAll(vendaProdutos);
        dadosVendas.removeAll(dadosVendas);
        jTable29.removeAll();
        lblIcms.setText("");
        lblIss.setText("");
        lblIpi.setText("");
        lblValorTotal.setText("");
        txtDescontoVendaServico.setSelectedIndex(0);
        txtDinheiro.setText("");
        txtCartao.setText("");
        txtTroco.setText("");
        txtDinheiro.setEnabled(false);
        txtCartao.setEnabled(false);
        txtTroco.setEnabled(false);
        cbD.setSelected(false);
        cbCC.setSelected(false);
        cbCD.setSelected(false);
        cA.setText("");
        cB.setText("");
        cC.setText("");
        cD.setText("");
        cE.setText("");
        cF.setText("");
        VerificarCodigo();
        JOptionPane.showMessageDialog(null, "Operação realizada com sucesso");

    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void cbDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDMouseClicked
        tipoPagamento();
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //    txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //    txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            //    txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            //    txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //     txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }

    }//GEN-LAST:event_cbDMouseClicked

    private void cbCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCCMouseClicked
        tipoPagamento();
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
    }//GEN-LAST:event_cbCCMouseClicked

    private void cbCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCDMouseClicked
        tipoPagamento();
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //  txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            // txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            // txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            //txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
    }//GEN-LAST:event_cbCDMouseClicked

    private void txtDescontoVendaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoVendaServicoActionPerformed
        DecimalFormat df = new DecimalFormat("0.##");
        x = 0;
        z = x;
        vl2 = 0;
        //z = z - (z * vl2 / 100);
        icms = 0;
        icms1 = icms;
        iss1 = 0;
        iss2 = iss1;
        ipi1 = 0;
        ipi2 = ipi1;
        String A = ""; //esvazia o arraylist dadosPessoa e, conseguentemente, esvazia a jTable.
        LTB2();
        //preenche a jTable com os dados restantes do arraylist pessoas.

        for (int i = 0; i < vendas.size(); i++) {
            PT2(vendas.get(i).getA(), vendas.get(i).getB(), vendas.get(i).getC(), vendas.get(i).getD(), vendas.get(i).getE(),
                    vendas.get(i).getF(), vendas.get(i).getG(), vendas.get(i).getH(), vendas.get(i).getJ());
        }
        int O = lblValorTotal.getText().length();
        if (O > 0) {
            A = lblValorTotal.getText().substring(2, O).replace(",", ".");
        } else {
            A = "0";
        }
        double aux = 0, aux2 = Double.parseDouble(A), aux3 = 0;

        if (txtDescontoVendaServico.getSelectedItem() == "0%") {
            aux = 0;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "5%") {
            aux = 5;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "10%") {
            aux = 10;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "15%") {
            aux = 15;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "20%") {
            aux = 20;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "25%") {
            aux = 25;
        }

        txtDescontoVendaServico.updateUI();

        aux3 = aux2 - (aux2 * aux / 100);

        lblValorTotal.setText("R$ " + df.format(aux3));
    }//GEN-LAST:event_txtDescontoVendaServicoActionPerformed

    private void txtDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DecimalFormat df = new DecimalFormat("0.##");
            double aux = 0, aux2 = 0, aux3 = 0;
            int tt = lblValorTotal.getText().length();

            aux = Double.parseDouble(txtDinheiro.getText().replace(",", "."));
            aux2 = Double.parseDouble(lblValorTotal.getText().substring(2, tt).replace(",", "."));

            if (aux > aux2) {
                aux3 = aux - aux2;

                btnFinalizarVenda.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
            }

            txtTroco.setText("R$ " + df.format(aux3));
        }
    }//GEN-LAST:event_txtDinheiroKeyPressed

    //</editor-fold>
    public String VerificarCodigo() {
        DAO dao = new DAO();
        text = GerarCodigo();

        try {
            while (txt = false) {
                dao.executaSQL("select * from vendas where codigoVenda = " + text);
                txt = dao.resultSet.first();
            }
            lbloCodVenda.setText(text);
            txt = false;
            return text;
        } catch (SQLException erro) {

            return "";
        }
    }

    public void preencherTabela(String SQL) {
        DAO dao = new DAO();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Descição", "Tipo", "Data da Compra", "Valor de Venda", "icsm", "iss", "ipi", "Estoque", "situação", "idProduto", "idlote"};
        dao.executaSQL(SQL);
        try {
            dao.resultSet.first();
            do {
                if(Integer.parseInt(dao.resultSet.getString("qtdEstoque")) > 0)
                dados.add(new Object[]{dao.resultSet.getString("nomeProduto"), dao.resultSet.getString("descricao"), dao.resultSet.getString("tipoProduto"), dao.resultSet.getString("dataCompra"),
                    dao.resultSet.getString("valorVenda"), dao.resultSet.getString("icms"), dao.resultSet.getString("iss"), dao.resultSet.getString("ipi"),
                    dao.resultSet.getString("qtdEstoque"), dao.resultSet.getString("situacaoProduto"), dao.resultSet.getString("idprodutos"), dao.resultSet.getString("idLote")});
            } while (dao.resultSet.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Operação Cancelada");
        }

        ModeloTabela model = new ModeloTabela(dados, colunas);
        jTable2.setModel(model);

        jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(6).setResizable(false);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(7).setResizable(false);

        jTable2.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela

    }

    public void PT2(String produto, String qtd, String desconto, String vlUnitario, String vlParcial, String icmsx, String issx, String ipix, String idLote) {
        //Calcular valores
        //calcular impostos

        DecimalFormat df = new DecimalFormat("0.##");

        String[] col = new String[]{"Produto", "Quantidade", "Desconto", "Valor Unitário", "Valor", "icsm", "iss", "ipi", "idLote"};
        try {
            dadosVendas.add(new Object[]{produto, qtd, desconto, vlUnitario, vlParcial, icmsx, issx, ipix, idLote});

            x = Double.parseDouble(vlParcial);
            z += x;
            vl2 = Double.parseDouble(desconto);
            //z = z - (z * vl2 / 100);
            icms = Double.parseDouble(icmsx);

            icms1 += x * (icms / 100);
            iss1 = Double.parseDouble(issx);
            iss2 += x * (iss1 / 100);
            ipi1 = Double.parseDouble(ipix);
            ipi2 += x * (ipi1 / 100);

            double qq = Desconto();
            z = z - (z * qq / 100);

            lblIcms.setText("R$ " + df.format(icms1));
            lblIss.setText("R$ " + df.format(iss2));
            lblIpi.setText("R$ " + df.format(ipi2));
            lblValorTotal.setText("R$ " + df.format(z));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        TabelaModelo2 model = new TabelaModelo2(dadosVendas, col);
        jTable29.setModel(model);

        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(1).setResizable(false);
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela

    }

    // <editor-fold defaultstate="collapsed" desc="calculo">
    public String calcular(String vlUnitario, String qtd, String desconto) {
        float q = Float.parseFloat(vlUnitario), w = Float.parseFloat(qtd), r = Float.parseFloat(desconto);

        float t = q * w;
        if ("".equals(desconto) || "0".equals(desconto)) {

        } else {
            t = t - (t * r / 100);
        }
        return Float.toString(t);
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="gerar codigo de venda">
    public String GerarCodigo() {
        Random cod = new Random();
        int num = 0;
        do {
            num = cod.nextInt(99999999);
        } while (num < 10000000);
        return Integer.toString(num);
    }

    //</editor-fold>
    public double Desconto() {
        double aux = 0;
        if (txtDescontoVendaServico.getSelectedItem() == "0%") {
            aux = 0;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "5%") {
            aux = 5;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "10%") {
            aux = 10;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "15%") {
            aux = 15;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "20%") {
            aux = 20;
        }
        if (txtDescontoVendaServico.getSelectedItem() == "25%") {
            aux = 25;
        }
        return aux;
    }

    // <editor-fold defaultstate="collapsed" desc="Tipo Pagamento">
    public void tipoPagamento() {
        if (cbD.isSelected()) {
            tp = "1";

        } else {
            tp = "0";

        }
        if (cbCC.isSelected()) {
            tp = "2";

        }
        if (cbCD.isSelected()) {
            tp = "3";

        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "4";

        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            tp = "0";
        }
    }

    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="LimparTabela pesquisa">
    public void LimparTabela() {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Descição", "Tipo", "Data da Compra", "Valor de Venda", "icsm", "iss", "ipi", "Estoque", "situação", "idProdutos", "idLote"};

        try {

            dados.add(new Object[]{"", "", "", "", "", "", "", "", "", "", "", ""});
            dados.removeAll(dados);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + "Ñ DEU");
        }

        ModeloTabela model = new ModeloTabela(dados, colunas);
        jTable2.setModel(model);

        jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(6).setResizable(false);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(7).setResizable(false);
        jTable2.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(8).setResizable(false);
        jTable2.getColumnModel().getColumn(9).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(9).setResizable(false);
        jTable2.getColumnModel().getColumn(10).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(10).setResizable(false);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(11).setResizable(false);

        jTable2.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }

    public void LTB2() {
        String[] col = new String[]{"Produto", "Quantidade", "Desconto", "Valor Unitário", "Valor", "icsm", "iss", "ipi", "idLote"};
        //esvazia o arraylist dadosPessoa.
        dadosVendas.removeAll(dadosVendas);
        //evazia a jTable, add dadosPessoa (sem dados).
        TabelaModelo2 modelo = new TabelaModelo2(dadosVendas, col);
        jTable29.setModel(modelo); // recebe o modelo criado
        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable29.getColumnModel().getColumn(0).setResizable(false);
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(150);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(1).setResizable(true);  // não permite alterar o tamanho da coluna 
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Limpar campo 1">
    public void Limpar1() {
        txtQtdVenda.setText("");
        txtDescontoVenda.setSelectedIndex(0);
        lblValorParcial.setText("");

        LimparTabela();

    }

    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="PesquisaQtd1">
    public boolean verificarQtd(String id,String Lote) {
        DAO dao = new DAO();
        int aux = dao.PesquisaEstoque(id, Lote);
        if (aux < Integer.parseInt(txtQtdVenda.getText())) {
            JOptionPane.showMessageDialog(null, "Estoque insuficiente");
            return false;
        }
        return true;
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnPesquisa1;
    private javax.swing.JButton btnPesquisa2;
    private javax.swing.JLabel cA;
    private javax.swing.JLabel cB;
    private javax.swing.JLabel cC;
    private javax.swing.JLabel cD;
    private javax.swing.JLabel cE;
    private javax.swing.JLabel cF;
    private javax.swing.JButton calcular;
    private javax.swing.JCheckBox cbCC;
    private javax.swing.JCheckBox cbCD;
    private javax.swing.JCheckBox cbD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable29;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblIcms;
    private javax.swing.JLabel lblIdlote;
    private javax.swing.JLabel lblIdproduto;
    private javax.swing.JLabel lblIpi;
    private javax.swing.JLabel lblIss;
    private javax.swing.JLabel lblValorParcial;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lbloCodVenda;
    private javax.swing.JPanel panelTipoPag;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtCodigoVendedor;
    private javax.swing.JComboBox<String> txtDescontoVenda;
    private javax.swing.JComboBox<String> txtDescontoVendaServico;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtPesquisaProdutoVenda;
    private javax.swing.JTextField txtPesqusiaTipoVenda;
    private javax.swing.JTextField txtQtdVenda;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
