/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ModeloTabela;
import Controller.OrdemProdutosController;
import Controller.vendaProdutosController;
import Models.Cliente;
import Models.DAO;
import Models.OrdemProdutos;
import Models.TabelaModelo2;
import Models.ValidarCPF;
import Models.Venda;
import Models.VendaProdutos;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

public class TelaOrdemServico extends javax.swing.JInternalFrame {

    ArrayList dadosVendas = new ArrayList();
    String tp, text, sql, a = "", b = "", c = "", d = "", e = "", f = "", g = "", h = "";
    boolean txt, verificar, c1 = false, c2 = false;
    ArrayList<Venda> vendas = new ArrayList<>();
    ArrayList<OrdemProdutos> vendaProdutos = new ArrayList<>();
    double x = 0, z, vl, vl2, icms1, icms, iss1, iss2, ipi1, ipi2, yy;

    public TelaOrdemServico() {
        initComponents();
        VerificarCodigo();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date agr = new Date();

        String A = df.format(agr).substring(0, 4);
        String B = df.format(agr).substring(5, 7);
        String C = df.format(agr).substring(8, 10);
        String Entrega = C + "/" + B + "/" + A;
        txtDataSolicitacao.setText(Entrega);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCodOrdem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNomeCli = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbServico = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbPrioridade = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPesquisaCpf = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        lblTelCli = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable29 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        btnPesquisaProduto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPesqusiaTipo = new javax.swing.JTextField();
        btnPesquisaTipo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblValorParcial = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        txtDencontoProd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnFinalizarOrdem = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        cbD = new javax.swing.JCheckBox();
        cbCC = new javax.swing.JCheckBox();
        cbCD = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        txtCodVendedor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        lblSomaParcial = new javax.swing.JLabel();
        txtDataSolicitacao = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblIcms = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblIpi = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblIss = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lblFK = new javax.swing.JLabel();
        txtDescontoGeral = new javax.swing.JComboBox<>();
        txtDataEntrega = new javax.swing.JFormattedTextField();
        txtValorServico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ORDEM DE SERVIÇO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ordem_tela.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nº :");

        lblCodOrdem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nome do Cliente :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("CPF :");

        lblNomeCli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Tipo de Serviço :");

        cbServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reparo", "Manutenção" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Prioridade :");

        cbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta", "Emergencial" }));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Data de Solicitação :");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Data de Entrega :");

        btnPesquisaCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisaCpf.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisaCpf.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisaCpf.setPreferredSize(new java.awt.Dimension(30, 30));
        btnPesquisaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCpfActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Descrição do Problema");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Telefone para Contato:");

        lblTelCli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTable29.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable29MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable29);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Nome do produto:");

        btnPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisaProduto.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisaProduto.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisaProduto.setPreferredSize(new java.awt.Dimension(30, 30));
        btnPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaProdutoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Tipo de Produto :");

        btnPesquisaTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisaTipo.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisaTipo.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisaTipo.setPreferredSize(new java.awt.Dimension(30, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Quantidade :");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Desconto:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Valor :");

        lblValorParcial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addVenda.png"))); // NOI18N
        btnAddProduto.setMaximumSize(new java.awt.Dimension(50, 50));
        btnAddProduto.setMinimumSize(new java.awt.Dimension(50, 50));
        btnAddProduto.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtDencontoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDencontoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesqusiaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtPesqusiaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCalcular)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(txtDencontoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Valor do Serviço :");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Desconto:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Valor Total:");

        lblValorTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        btnFinalizarOrdem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ordemServicoConfima.png"))); // NOI18N
        btnFinalizarOrdem.setText("Finalizar");
        btnFinalizarOrdem.setMaximumSize(new java.awt.Dimension(50, 50));
        btnFinalizarOrdem.setMinimumSize(new java.awt.Dimension(50, 50));
        btnFinalizarOrdem.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFinalizarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarOrdemActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Tipo de Pagamento:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Dinheiro:");

        txtDinheiro.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Cartão :");

        txtCartao.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCartao)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbD.setText("Dinheiro");
        cbD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDMouseClicked(evt);
            }
        });

        cbCC.setText("Cartão de Crédito");
        cbCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCCMouseClicked(evt);
            }
        });

        cbCD.setText("Cartão de Débito");
        cbCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCDMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Código do Vendedor :");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setText("Valor parcial de produtos:");

        lblSomaParcial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtCpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfClienteKeyTyped(evt);
            }
        });

        lblIcms.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("ISS :");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("ICMS :");

        lblIpi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("IPI :");

        lblIss.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIpi, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(lblIss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(lblIpi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estornoConfirma.png"))); // NOI18N
        btnCancelar.setText("Remover Item");
        btnCancelar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCancelar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbl1.setText("jLabel24");

        lbl2.setText("jLabel24");

        lbl3.setText("jLabel24");

        lbl4.setText("jLabel24");

        lbl5.setText("jLabel24");

        lbl9.setText("jLabel24");

        lblFK.setText("jLabel24");

        txtDescontoGeral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%" }));
        txtDescontoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoGeralActionPerformed(evt);
            }
        });

        try {
            txtDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Troco :");

        txtTroco.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblCodOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(201, 201, 201))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDataSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDataEntrega))))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(514, 514, 514))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSomaParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbD)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbCC)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbCD))
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtDescontoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnFinalizarOrdem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFK)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel23)
                                    .addComponent(txtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtDescontoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbD)
                                    .addComponent(cbCC)
                                    .addComponent(cbCD)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSomaParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFinalizarOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblCodOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtDataSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(btnPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(lblTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addComponent(lbl5)
                    .addComponent(lbl9)
                    .addComponent(lblFK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Botão Pesquisa CPF"> 
    private void btnPesquisaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCpfActionPerformed

        ValidarCPF valCpf = new ValidarCPF() {
        };
        if (valCpf.validaCPF(txtCpfCliente.getText()) == true) {
            // jLabelValCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/102.png")));
            DAO dao = new DAO();
            dao.bd.getConnection();
            String buscaCpf = txtCpfCliente.getText();
            PreparedStatement sta;
            try {
                sta = dao.bd.connection.prepareStatement("select * from cliente where cpf = ? limit 1");
                sta.setString(1, buscaCpf);
                ResultSet rs = sta.executeQuery();
                while (rs.next()) {
                    JOptionPane.showMessageDialog(null, "CPF já cadastrado anteriormente!");
                    txtCpfCliente.setText("");
                    txtCpfCliente.grabFocus();
                }
            } catch (SQLException ex) {
            }
        } else {

            OrdemProdutosController OP = new OrdemProdutosController();
            lblNomeCli.setText(OP.pesquisarCliente(txtCpfCliente.getText()));
            lblTelCli.setText(OP.pesquisarCliente2(txtCpfCliente.getText()));
        }
    }//GEN-LAST:event_btnPesquisaCpfActionPerformed
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Botão Calcular"> 
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String aux = "";
        if (txtDencontoProd.getSelectedItem() == "0%") {
            aux = "0";
        }
        if (txtDencontoProd.getSelectedItem() == "5%") {
            aux = "5";
        }
        if (txtDencontoProd.getSelectedItem() == "10%") {
            aux = "10";
        }
        if (txtDencontoProd.getSelectedItem() == "15%") {
            aux = "15";
        }
        if (txtDencontoProd.getSelectedItem() == "20%") {
            aux = "20";
        }
        if (txtDencontoProd.getSelectedItem() == "25%") {
            aux = "25";
        }

        lblValorParcial.setText(calcular(b, txtQtd.getText(), aux));
    }//GEN-LAST:event_btnCalcularActionPerformed
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Botão adicionar carrinho"> 
    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        OrdemProdutosController op = new OrdemProdutosController();
        vendaProdutosController vp = new vendaProdutosController();
        String aux = "";

        if (txtDencontoProd.getSelectedItem() == "0%") {
            aux = "0";
        }
        if (txtDencontoProd.getSelectedItem() == "5%") {
            aux = "5";
        }
        if (txtDencontoProd.getSelectedItem() == "10%") {
            aux = "10";
        }
        if (txtDencontoProd.getSelectedItem() == "15%") {
            aux = "15";
        }
        if (txtDencontoProd.getSelectedItem() == "20%") {
            aux = "20";
        }
        if (txtDencontoProd.getSelectedItem() == "25%") {
            aux = "25";
        }

        boolean vf = verificarQtd(f, h);

        if (vf) {
            preencherTabela2(a, txtQtd.getText(), aux, b, lblValorParcial.getText(), c, d, e, h);
            vendas.add(vp.preencherArray3(a, txtQtd.getText(), aux, b, lblValorParcial.getText(), c, d, e, f));
            vendaProdutos.add(op.preencherCarrinhoOrdem(h, txtQtd.getText(), aux, lblValorParcial.getText(),
                    lblCodOrdem.getText()));

            Limpar1();
        } else {
        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Botão remover item"> 
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        x = 0;
        z = x;
        vl2 = 0;
        //z = z - (z * vl2 / 100);
        icms = 0;
        icms1 = icms;
        iss1 = 0;
        iss2 = iss1;
        ipi1 = 0;
        ipi2 = ipi1;
        lblValorTotal.setText("");
        lblIcms.setText("");
        lblIss.setText("");
        lblIpi.setText("");
        cbD.setSelected(false);
        cbCC.setSelected(false);
        cbCD.setSelected(false);
        txtDinheiro.setText("");
        txtCartao.setText("");
        txtTroco.setText("");

        if (!lbl1.getText().equals("")) {
            //remove do arraylist pessoas os dados da linha selecionada.
            int x = vendas.size();
            for (int i = 0; i < vendas.size(); i++) {
                if (vendas.get(i).getA().equals(lbl1.getText())) {
                    vendas.remove(i);
                    vendaProdutos.remove(i);
                    lbl1.setText("");
                }
            }

            //esvazia o arraylist dadosPessoa e, conseguentemente, esvazia a jTable.
            limparTabela2();
            //preenche a jTable com os dados restantes do arraylist pessoas.
            for (int i = 0; i < vendas.size(); i++) {
                preencherTabela2(vendas.get(i).getA(), vendas.get(i).getB(), vendas.get(i).getC(), vendas.get(i).getD(), vendas.get(i).getE(),
                        vendas.get(i).getF(), vendas.get(i).getG(), vendas.get(i).getH(), vendas.get(i).getJ());
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Botão Finalizar"> 
    private void btnFinalizarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarOrdemActionPerformed

        OrdemProdutosController opc = new OrdemProdutosController();
        DAO dao = new DAO();
        String codvend = dao.buscarFuncionario(txtCodVendedor.getText());

        if (codvend != ";") {
            if (txtDinheiro.getText() != "" || txtDinheiro.getText() != null) {

                String idCli = dao.BuscarIdcli(txtCpfCliente.getText());
                String aux = "", dinheiro = "", cartao = "", troco = "", servico = "";
                double aux2 = 0;

                tipoPagamento();

                if (txtDescontoGeral.getSelectedItem() == "0%") {
                    aux = "0";
                }
                if (txtDescontoGeral.getSelectedItem() == "5%") {
                    aux = "5";
                }
                if (txtDescontoGeral.getSelectedItem() == "10%") {
                    aux = "10";
                }
                if (txtDescontoGeral.getSelectedItem() == "15%") {
                    aux = "15";
                }
                if (txtDescontoGeral.getSelectedItem() == "20%") {
                    aux = "20";
                }
                if (txtDescontoGeral.getSelectedItem() == "25%") {
                    aux = "25";
                }

                String A = txtDataEntrega.getText().substring(0, 2);
                String B = txtDataEntrega.getText().substring(3, 5);
                String C = txtDataEntrega.getText().substring(6, 10);
                String Entrega = C + "-" + B + "-" + A;

                String D = txtDataSolicitacao.getText().substring(0, 2);
                String E = txtDataSolicitacao.getText().substring(3, 5);
                String F = txtDataSolicitacao.getText().substring(6, 10);
                String Solicitacao = F + "-" + E + "-" + D;

                int ic = lblIcms.getText().length();
                int is = lblIss.getText().length();
                int ip = lblIpi.getText().length();
                int vlt = lblValorTotal.getText().length();
                int din = txtDinheiro.getText().length();
                int car = txtCartao.getText().length();

                int vls = txtValorServico.getText().length();

                if (din > 0) {
                    dinheiro = txtDinheiro.getText().replace(",", ".");
                } else {
                    dinheiro = "0";
                }
                if (car > 0) {
                    cartao = txtCartao.getText().replace(",", ".");
                } else {
                    cartao = "0";
                }

                if (vls > 0) {
                    servico = txtValorServico.getText().replace(",", ".");
                } else {
                    servico = "0";
                }

                String icms = lblIcms.getText().substring(2, ic).replace(",", ".");
                String iss = lblIss.getText().substring(2, is).replace(",", ".");
                String ipi = lblIpi.getText().substring(2, ip).replace(",", ".");
                String valorT = lblValorTotal.getText().substring(2, vlt).replace(",", ".");

                DecimalFormat dc = new DecimalFormat("##.##");
                aux2 = (Double.parseDouble(dinheiro)) - (Double.parseDouble(valorT));
                txtTroco.setText("R$ " + dc.format(aux2));

                int tro = txtTroco.getText().length();
                if (tro > 0) {
                    troco = txtTroco.getText().substring(2, tro).replace(",", ".");
                } else {
                    troco = "0";
                }

                tipoPagamento();

                opc.salvarOrdemServico(cbServico.getSelectedItem().toString(), servico, Entrega, Solicitacao, Integer.toString(cbPrioridade.getSelectedIndex()),
                        txtDescricao.getText(), tp, txtCodVendedor.getText(), icms, iss, ipi,
                        valorT, txtCpfCliente.getText(), lblCodOrdem.getText(), idCli, codvend, "", "", aux, dinheiro,
                        cartao, troco);

                for (int i = 0; i < vendaProdutos.size(); i++) {
                    opc.salvarLoteOrdem(vendaProdutos.get(i).getFKlote(), vendaProdutos.get(i).getQtd(), vendaProdutos.get(i).getDesconto(),
                            vendaProdutos.get(i).getValorParcial(), lblCodOrdem.getText());
                }
                JOptionPane.showMessageDialog(null, "Operação realizada com sucesso");

                int n = JOptionPane.showConfirmDialog(
                        null, "Deseja realizar uma nova compra?",
                        "Nova Compra",
                        JOptionPane.YES_NO_OPTION);

                if (n == 0) {
                    VerificarCodigo();
                    vendas.removeAll(vendas);
                    vendaProdutos.removeAll(vendaProdutos);
                    dadosVendas.removeAll(dadosVendas);
                    jTable29.removeAll();
                    lblIcms.setText("");
                    lblIss.setText("");
                    lblIpi.setText("");
                    lblValorTotal.setText("");
                    txtDescontoGeral.setSelectedIndex(0);
                    txtDinheiro.setText("");
                    txtCartao.setText("");
                    txtTroco.setText("");
                    txtDinheiro.setEnabled(false);
                    txtCartao.setEnabled(false);
                    txtTroco.setEnabled(false);
                    cbD.setSelected(false);
                    cbCC.setSelected(false);
                    cbCD.setSelected(false);
                    a = "";
                    b = "";
                    c = "";
                    d = "";
                    e = "";
                    f = "";
                    txtDescontoGeral.setEnabled(true);
                    lblSomaParcial.setText("");
                    txtValorServico.setText("");
                    txtDataEntrega.setText("");
                    txtCpfCliente.setText("");
                    cbPrioridade.setSelectedIndex(-1);
                    cbServico.setSelectedIndex(-1);
                    lblTelCli.setText("");
                    txtCodVendedor.setText("");
                    txtDescricao.setText("");
                    lblValorTotal.setText("");
                    VerificarCodigo();
                } else {
                    this.dispose();
                }
            }
        }

    }//GEN-LAST:event_btnFinalizarOrdemActionPerformed
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="JTable 2 evento"> 
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int linhaSelecionada = jTable2.getSelectedRow();
        a = (jTable2.getValueAt(linhaSelecionada, 0).toString());
        b = (jTable2.getValueAt(linhaSelecionada, 4).toString());
        c = (jTable2.getValueAt(linhaSelecionada, 5).toString());
        d = (jTable2.getValueAt(linhaSelecionada, 6).toString());
        e = (jTable2.getValueAt(linhaSelecionada, 7).toString());
        f = (jTable2.getValueAt(linhaSelecionada, 10).toString());
        h = (jTable2.getValueAt(linhaSelecionada, 11).toString());


    }//GEN-LAST:event_jTable2MouseClicked
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="JTable 29 evento"> 
    private void jTable29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable29MouseClicked

        int linhaSelecionada = jTable29.getSelectedRow();
        lbl1.setText(jTable29.getValueAt(linhaSelecionada, 0).toString());
        lbl2.setText(jTable29.getValueAt(linhaSelecionada, 1).toString());
        lbl3.setText(jTable29.getValueAt(linhaSelecionada, 2).toString());
        lbl4.setText(jTable29.getValueAt(linhaSelecionada, 3).toString());
        lbl5.setText(jTable29.getValueAt(linhaSelecionada, 4).toString());
        //lbl6.setText(jTable29.getValueAt(linhaSelecionada, 5).toString());
        //lbl7.setText(jTable29.getValueAt(linhaSelecionada, 6).toString());
        // lbl8.setText(jTable29.getValueAt(linhaSelecionada, 7).toString());
        lbl9.setText(jTable29.getValueAt(linhaSelecionada, 8).toString());
        lblFK.setText(jTable29.getValueAt(linhaSelecionada, 10).toString());

    }//GEN-LAST:event_jTable29MouseClicked

    private void cbDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDMouseClicked
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            // txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
    }//GEN-LAST:event_cbDMouseClicked

    private void cbCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCCMouseClicked
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //  txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            //    txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
    }//GEN-LAST:event_cbCCMouseClicked

    private void cbCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCDMouseClicked
        if (cbD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            txtCartao.setEnabled(false);
        } else {
            tp = "0";
            txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            txtDinheiro.setEnabled(false);
            //    txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            txtDinheiro.setEnabled(true);
            //    txtTroco.setEnabled(true);
            txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            cbD.setSelected(false);
            cbCC.setSelected(false);
            cbCD.setSelected(false);
            txtDinheiro.setEnabled(false);
            txtTroco.setEnabled(false);
            txtCartao.setEnabled(false);
        }
    }//GEN-LAST:event_cbCDMouseClicked

    private void txtDescontoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoGeralActionPerformed

        if (txtValorServico.getText() != "" || txtValorServico.getText() != null) {

            DecimalFormat df = new DecimalFormat("##.##");
            x = 0;
            z = x;
            yy = 0;
            vl2 = 0;
            //z = z - (z * vl2 / 100);
            icms = 0;
            icms1 = icms;
            iss1 = 0;
            iss2 = iss1;
            ipi1 = 0;
            ipi2 = ipi1;
            String A = "";
            lblSomaParcial.setText("");
            limparTabela2();

            for (int i = 0; i < vendas.size(); i++) {
                preencherTabela2(vendas.get(i).getA(), vendas.get(i).getB(), vendas.get(i).getC(), vendas.get(i).getD(), vendas.get(i).getE(),
                        vendas.get(i).getF(), vendas.get(i).getG(), vendas.get(i).getH(), vendas.get(i).getJ());

            }

            int O = lblValorTotal.getText().length();
            if (O > 0) {
                A = lblValorTotal.getText().substring(2, O).replace(",", ".");
            } else {
                A = "0";
            }
            double Aa = Double.parseDouble(A);
            double Bb = Double.parseDouble(txtValorServico.getText());

            double aux = 0, aux2 = (Aa + Bb), aux3 = 0;

            if (txtDescontoGeral.getSelectedItem() == "0%") {
                aux = aux2 * 0;
            }
            if (txtDescontoGeral.getSelectedItem() == "5%") {
                aux = aux2 * 0.05;

            }
            if (txtDescontoGeral.getSelectedItem() == "10%") {
                aux = aux2 * 0.10;
            }
            if (txtDescontoGeral.getSelectedItem() == "15%") {
                aux = aux2 * 0.15;
            }
            if (txtDescontoGeral.getSelectedItem() == "20%") {
                aux = aux2 * 0.20;
            }
            if (txtDescontoGeral.getSelectedItem() == "25%") {
                aux = aux2 * 0.25;
            }

            txtDescontoGeral.updateUI();

            aux3 = aux2 - aux;

            lblValorTotal.setText("R$ " + df.format(aux2));
        } else {
            
            txtDescontoGeral.setSelectedIndex(0);
            lblValorTotal.setText("");
            JOptionPane.showMessageDialog(null, "Insira o valor do serviço"
            +"\n apenas números inteiros");
        }

    }//GEN-LAST:event_txtDescontoGeralActionPerformed

    private void btnPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaProdutoActionPerformed
        sql = "select * from produtos inner join Lote on idprodutos = FKprodutos where nomeProduto like '%" + txtPesquisaProduto.getText() + "%'";

        preencherTabela(sql);
    }//GEN-LAST:event_btnPesquisaProdutoActionPerformed

    private void txtCpfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfClienteKeyTyped
        if (txtCpfCliente.getText().length() > 10 && !(evt.getKeyChar() == KeyEvent.VK_DELETE || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            char input = evt.getKeyChar();
            if ((input < '0' || input > '9') && input != '\b') {
                evt.consume();
                JOptionPane.showMessageDialog(null, "Caractere inválido");
            }
        }
    }//GEN-LAST:event_txtCpfClienteKeyTyped
//</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Tabela 1">
    public void preencherTabela(String SQL) {
        DAO dao = new DAO();

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Descição", "Tipo", "Data da Compra", "Valor de Venda", "icsm", "iss", "ipi", "Estoque", "situação", "idProduto", "idlote",};
        dao.executaSQL(SQL);
        try {
            dao.resultSet.first();
            do {
                if (Integer.parseInt(dao.resultSet.getString("qtdEstoque")) > 0) {
                    dados.add(new Object[]{dao.resultSet.getString("nomeProduto"), dao.resultSet.getString("descricao"), dao.resultSet.getString("tipoProduto"), dao.resultSet.getString("dataCompra"),
                        dao.resultSet.getString("valorVenda"), dao.resultSet.getString("icms"), dao.resultSet.getString("iss"), dao.resultSet.getString("ipi"),
                        dao.resultSet.getString("qtdEstoque"), dao.resultSet.getString("situacaoProduto"), dao.resultSet.getString("idprodutos"), dao.resultSet.getString("idLote")});
                }
            } while (dao.resultSet.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "A tabela não pode retornar os dados");
        }

        ModeloTabela model = new ModeloTabela(dados, colunas);
        jTable2.setModel(model);

        jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(6).setResizable(false);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(7).setResizable(false);

        jTable2.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Tabela 2">
    public void preencherTabela2(String produto, String qtd, String desconto, String vlUnitario, String vlParcial, String icmsx, String issx, String ipix, String idLote) {
        //Calcular valores
        //calcular impostos
        DecimalFormat df = new DecimalFormat("0.##");
        String[] colunas = new String[]{"Produto", "Quantidade", "Desconto", "Valor Unitário", "Valor", "icsm", "iss", "ipi", "idLote"};
        try {
            dadosVendas.add(new Object[]{produto, qtd, desconto, vlUnitario, vlParcial, icmsx, issx, ipix, idLote});

            x = Double.parseDouble(vlParcial);
            z += x;
            yy += x;
            vl2 = Double.parseDouble(desconto);
            // = z - (z * vl2 / 100);
            icms = Double.parseDouble(icmsx);

            icms1 += x * (icms / 100);
            iss1 = Double.parseDouble(issx);
            iss2 += x * (iss1 / 100);
            ipi1 = Double.parseDouble(ipix);
            ipi2 += x * (ipi1 / 100);

            double qq = Desconto();
            z = z - (z * qq / 100);

            lblIcms.setText("R$ " + df.format(icms1));
            lblIss.setText("R$ " + df.format(iss2));
            lblIpi.setText("R$ " + df.format(ipi2));
            lblValorTotal.setText("R$ " + df.format(z));
            lblSomaParcial.setText("R$ " + df.format(yy));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        TabelaModelo2 model = new TabelaModelo2(dadosVendas, colunas);
        jTable29.setModel(model);

        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(1).setResizable(false);
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Calculo">
    public String calcular(String vlUnitario, String qtd, String desconto) {
        float q = Float.parseFloat(vlUnitario), w = Float.parseFloat(qtd), r = Float.parseFloat(desconto);

        float t = q * w;
        if ("".equals(desconto) || "0".equals(desconto)) {

        } else {
            t = t - (t * r / 100);
        }
        return Float.toString(t);
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="gerar codigo de Ordem de Serviço">
    public String GerarCodigo() {
        Random cod = new Random();
        int num = 0;
        do {
            num = cod.nextInt(99999999);
        } while (num < 10000000);
        return Integer.toString(num);
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Tipo Pagamento">
    public void tipoPagamento() {
        if (cbD.isSelected()) {
            tp = "1";
            //   txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            //  txtCartao.setEnabled(false);
        } else {
            tp = "0";
            //   txtDinheiro.setEnabled(false);
            ///  txtTroco.setEnabled(false);
            //  txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            //   txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            //  txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            //   txtDinheiro.setEnabled(false);
            //   txtTroco.setEnabled(false);
            //   txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            //   txtDinheiro.setEnabled(true);
            //   txtTroco.setEnabled(true);
            //   txtCartao.setEnabled(true);
        }
        //  if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
        //    JOptionPane.showMessageDialog(null, "Opção inválida");
        //   cbD.setSelected(false);
        //   cbCC.setSelected(false);
        //   cbCD.setSelected(false);
        //   txtDinheiro.setEnabled(false);
        // //   txtTroco.setEnabled(false);
        //   txtCartao.setEnabled(false);
        //  }

    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Verificar Código">
    public String VerificarCodigo() {
        DAO dao = new DAO();
        text = GerarCodigo();

        try {
            while (txt = false) {
                dao.executaSQL("select * from vendas where codigoVenda = " + text);
                txt = dao.resultSet.first();
            }
            lblCodOrdem.setText(text);
            txt = false;
            return text;
        } catch (SQLException erro) {

            return "";
        }
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Limpar tabela 2">
    public void limparTabela2() {
        String[] colunas = new String[]{"Produto", "Quantidade", "Desconto", "Valor Unitário", "Valor", "icsm", "iss", "ipi", "idLote"};
        //esvazia o arraylist dadosPessoa.
        dadosVendas.removeAll(dadosVendas);
        //evazia a jTable, add dadosPessoa (sem dados).
        ModeloTabela modelo = new ModeloTabela(dadosVendas, colunas);
        jTable29.setModel(modelo); // recebe o modelo criado
        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable29.getColumnModel().getColumn(0).setResizable(false);
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(150);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(1).setResizable(true);  // não permite alterar o tamanho da coluna 
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);
        //  jTable29.getColumnModel().getColumn(9).setPreferredWidth(50);
        ////   jTable29.getColumnModel().getColumn(9).setResizable(false);
        //   jTable29.getColumnModel().getColumn(10).setPreferredWidth(50);
        //    jTable29.getColumnModel().getColumn(10).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="LimparTabela pesquisa">
    public void LimparTabela() {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Descição", "Tipo", "Data da Compra", "Valor de Venda", "icsm", "iss", "ipi", "Estoque", "situação", "idProdutos", "idLote"};

        try {

            dados.add(new Object[]{"", "", "", "", "", "", "", ""});
            dados.removeAll(dados);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + "Ñ DEU");
        }

        ModeloTabela model = new ModeloTabela(dados, colunas);
        jTable2.setModel(model);

        jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(6).setResizable(false);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(7).setResizable(false);

        jTable2.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Limpar campo 1">
    public void Limpar1() {
        txtQtd.setText("");
        txtDencontoProd.setSelectedIndex(0);
        lblValorParcial.setText("");

        LimparTabela();

    }

    //</editor-fold>
    public double Desconto() {
        double aux = 0;
        if (txtDescontoGeral.getSelectedItem() == "0%") {
            aux = 0;
        }
        if (txtDescontoGeral.getSelectedItem() == "5%") {
            aux = 5;
        }
        if (txtDescontoGeral.getSelectedItem() == "10%") {
            aux = 10;
        }
        if (txtDescontoGeral.getSelectedItem() == "15%") {
            aux = 15;
        }
        if (txtDescontoGeral.getSelectedItem() == "20%") {
            aux = 20;
        }
        if (txtDescontoGeral.getSelectedItem() == "25%") {
            aux = 25;
        }
        return aux;
    }

    // <editor-fold defaultstate="collapsed" desc="Verificar Campos Vazios">
    public boolean VerificarCampos() {
        if (txtDataEntrega.getText().equals("")) {
            verificar = true;
        }
        if (txtDataSolicitacao.getText().equals("")) {
            verificar = true;
        }
        if (txtValorServico.getText().equals("")) {
            verificar = true;
        }
        return verificar;
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="PesquisaQtd1">
    public boolean verificarQtd(String id, String Lote) {
        DAO dao = new DAO();
        int aux = dao.PesquisaEstoque(id, Lote);
        if (aux < Integer.parseInt(txtQtd.getText())) {
            JOptionPane.showMessageDialog(null, "Estoque insuficiente");
            return false;
        }
        return true;
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Java - Do not Modify"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarOrdem;
    private javax.swing.JButton btnPesquisaCpf;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnPesquisaTipo;
    private javax.swing.JCheckBox cbCC;
    private javax.swing.JCheckBox cbCD;
    private javax.swing.JCheckBox cbD;
    private javax.swing.JComboBox<String> cbPrioridade;
    private javax.swing.JComboBox<String> cbServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable29;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblCodOrdem;
    private javax.swing.JLabel lblFK;
    private javax.swing.JLabel lblIcms;
    private javax.swing.JLabel lblIpi;
    private javax.swing.JLabel lblIss;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblSomaParcial;
    private javax.swing.JLabel lblTelCli;
    private javax.swing.JLabel lblValorParcial;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtCodVendedor;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JFormattedTextField txtDataEntrega;
    private javax.swing.JTextField txtDataSolicitacao;
    private javax.swing.JComboBox<String> txtDencontoProd;
    private javax.swing.JComboBox<String> txtDescontoGeral;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtPesqusiaTipo;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
