/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ModeloTabela;
import Controller.vendaProdutosController;
import Models.DAO;
import Models.TabelaModelo2;
import Models.Venda;
import Models.VendaProdutos;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author 03758479100
 */
public class TelaEstornoVendas extends javax.swing.JInternalFrame {

    String sql = "", tp = "", sql1 = "";
    double x = 0, z, vl, vl2, icms1, icms, iss1, iss2, ipi1, ipi2;
    double x22 = 0, z22, vl22, vl222, icms122, icms22, iss122, iss222, ipi122, ipi222;
    ArrayList<Venda> vendas = new ArrayList<>();
    ArrayList dadosVendas = new ArrayList();
    ArrayList dadosVendas2 = new ArrayList();
    ArrayList<VendaProdutos> vendaProdutos = new ArrayList<>();
    ArrayList<VendaProdutos> vendaProdutos2 = new ArrayList<>();

    public TelaEstornoVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodVenda = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblValorTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblIpi = new javax.swing.JLabel();
        lblIcms = new javax.swing.JLabel();
        lblIss = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbD = new javax.swing.JCheckBox();
        lblValor = new javax.swing.JLabel();
        cbCC = new javax.swing.JCheckBox();
        cbCD = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        lblDescontoGeral = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblDataVenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable29 = new javax.swing.JTable();
        lblValorTotalx = new javax.swing.JLabel();
        cbCC1 = new javax.swing.JCheckBox();
        cbCD1 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblImposto3 = new javax.swing.JLabel();
        lblImposto1 = new javax.swing.JLabel();
        lblImposto2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblValorParcialx = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblDescontoGeralx = new javax.swing.JLabel();
        cbD1 = new javax.swing.JCheckBox();
        btnEstorno = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        lbltipoPag = new javax.swing.JLabel();
        lblestorno = new javax.swing.JLabel();
        lblFKfuncionario = new javax.swing.JLabel();
        lblCodfuncionario = new javax.swing.JLabel();
        lblCodvenda = new javax.swing.JLabel();
        lblCodigoFunc = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lblCodigoFunc1 = new javax.swing.JLabel();
        lbltipoPag1 = new javax.swing.JLabel();
        lblestorno1 = new javax.swing.JLabel();
        lblFKfuncionario1 = new javax.swing.JLabel();
        lblCodfuncionario1 = new javax.swing.JLabel();
        lblCodvenda1 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblDataVendax = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ESTORNO DE VENDAS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estornoVenda_tela.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código de Venda :");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa3.png"))); // NOI18N
        btnPesquisar.setMaximumSize(new java.awt.Dimension(30, 30));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(30, 30));
        btnPesquisar.setPreferredSize(new java.awt.Dimension(30, 30));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        lblValorTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Impostos"));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("ICMS :");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("ISS :");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("IPI :");

        lblIpi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblIcms.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblIss.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIpi, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(lblIss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(lblIpi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Valor  :");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Desconto:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Valor Total:");

        cbD.setText("Dinheiro");
        cbD.setEnabled(false);

        lblValor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        cbCC.setText("Cartão de Crédito");
        cbCC.setEnabled(false);

        cbCD.setText("Cartão de Débito");
        cbCD.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Tipo de Pagamento:");

        lblDescontoGeral.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Data da Venda :");

        lblDataVenda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(lblDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescontoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCD)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lblDescontoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbD)
                            .addComponent(cbCC)
                            .addComponent(cbCD))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable29.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable29MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable29);

        lblValorTotalx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        cbCC1.setText("Cartão de Crédito");
        cbCC1.setEnabled(false);

        cbCD1.setText("Cartão de Débito");
        cbCD1.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setText("Valor  :");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Impostos"));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("ICMS :");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("ISS :");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("IPI :");

        lblImposto3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblImposto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblImposto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImposto3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImposto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImposto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImposto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(lblImposto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(lblImposto3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setText("Valor Total:");

        lblValorParcialx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel40.setText("Tipo de Pagamento:");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setText("Desconto:");

        lblDescontoGeralx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        cbD1.setText("Dinheiro");
        cbD1.setEnabled(false);

        btnEstorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estornoVenda.png"))); // NOI18N
        btnEstorno.setText("Gerar Estorno");
        btnEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstornoActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setText("Observação/Motivo :");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane3.setViewportView(txtObservacao);

        lbltipoPag.setText("jLabel2");

        lblestorno.setText("jLabel2");

        lblFKfuncionario.setText("jLabel2");

        lblCodfuncionario.setText("jLabel2");

        lblCodvenda.setText("jLabel2");

        lblCodigoFunc.setText("jLabel2");

        btnCancelar.setText("Remover item");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbl1.setText("jLabel3");

        lbl2.setText("jLabel3");

        lbl3.setText("jLabel3");

        lbl4.setText("jLabel3");

        lbl5.setText("jLabel3");

        lbl6.setText("jLabel3");

        lblCodigoFunc1.setText("jLabel2");

        lbltipoPag1.setText("jLabel2");

        lblestorno1.setText("jLabel2");

        lblFKfuncionario1.setText("jLabel2");

        lblCodfuncionario1.setText("jLabel2");

        lblCodvenda1.setText("jLabel2");

        lbl7.setText("jLabel3");

        lbl8.setText("jLabel3");

        lbl9.setText("jLabel3");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Data da Venda :");

        lblDataVendax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbltipoPag)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblestorno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblFKfuncionario)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblCodfuncionario)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblCodvenda)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblCodigoFunc))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescontoGeralx, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorParcialx, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbD1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCC1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCD1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEstorno)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblValorTotalx, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataVendax, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltipoPag1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblestorno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFKfuncionario1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodfuncionario1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodvenda1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodigoFunc1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl9)))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(lblValorParcialx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(lblDescontoGeralx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40)
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbD1)
                                            .addComponent(cbCC1)
                                            .addComponent(cbCD1))
                                        .addGap(0, 5, Short.MAX_VALUE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(lblValorTotalx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataVendax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEstorno)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipoPag)
                    .addComponent(lblestorno)
                    .addComponent(lblFKfuncionario)
                    .addComponent(lblCodfuncionario)
                    .addComponent(lblCodvenda)
                    .addComponent(lblCodigoFunc))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipoPag1)
                    .addComponent(lblestorno1)
                    .addComponent(lblFKfuncionario1)
                    .addComponent(lblCodfuncionario1)
                    .addComponent(lblCodvenda1)
                    .addComponent(lblCodigoFunc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addComponent(lbl5)
                    .addComponent(lbl6)
                    .addComponent(lbl7)
                    .addComponent(lbl9)
                    .addComponent(lbl8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        sql = "select * from vendas inner join lotevendas on codVenda = FKvendas "
                + "inner join lote on FKlote = idLote "
                + "inner join produtos on FKprodutos = idprodutos where codigoVenda = '" + txtCodVenda.getText() + "'";
        preencherTabela(sql);
        lblestorno.setText(txtCodVenda.getText());
        tp = lbltipoPag.getText();
        if (tp.equals("1")) {
            cbD.setSelected(true);
            cbD1.setSelected(true);
        }
        if (tp.equals("2")) {
            cbCC.setSelected(true);
            cbCC1.setSelected(true);
        }
        if (tp.equals("3")) {
            cbCD.setSelected(true);
            cbCD1.setSelected(true);
        }

        // preencherTabela2(dadosVendas);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstornoActionPerformed
        vendaProdutosController vndP = new vendaProdutosController();
        DAO dao = new DAO();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date agr = new Date();
        // String codvend = dao.buscarFuncionario(txtCodigoVendedor.getText());
        //  if (codvend.equals(null)) {
        //     JOptionPane.showMessageDialog(null, "insira um codigo valido");

        //  } else {
        tipoPagamento();
        vndP.salvarVenda(lblDescontoGeral.getText(), tp, lblDataVenda.getText(), txtObservacao.getText(), txtCodVenda.getText(), lblIcms.getText(), lblIss.getText(),
                lblIpi.getText(), lblFKfuncionario.getText(), txtCodVenda.getText(), lblCodfuncionario.getText(), lblValorTotal.getText());

        for (int i = 0; i < vendaProdutos2.size(); i++) {
            vndP.salvarLoteVenda(vendaProdutos2.get(i).getFkLoteVendas(), vendaProdutos2.get(i).getQtd(), vendaProdutos2.get(i).getDescontoItemVendProduto(),
                    vendaProdutos2.get(i).getValorParcialVendProduto(),
                    txtCodVenda.getText());
            //   }
            
        }
        vndP.salvarVenda(lblDescontoGeralx.getText(), tp, lblDataVendax.getText(), "", "0", lblImposto1.getText(), lblImposto2.getText(),
                lblImposto3.getText(), lblFKfuncionario.getText(), txtCodVenda.getText(), lblCodfuncionario.getText(), lblValorTotalx.getText());

        for (int i = 0; i < vendaProdutos.size(); i++) {
            vndP.salvarLoteVenda(vendaProdutos.get(i).getFkLoteVendas(), vendaProdutos.get(i).getQtd(), vendaProdutos.get(i).getDescontoItemVendProduto(),
                    vendaProdutos.get(i).getValorParcialVendProduto(),
                    txtCodVenda.getText());
            //   }
            
        }

    }//GEN-LAST:event_btnEstornoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        if (!lbl1.getText().equals("")) {
            //remove do arraylist pessoas os dados da linha selecionada.
            int x = vendas.size();
            for (int i = 0; i < vendas.size(); i++) {
                if (vendas.get(i).getA().equals(lbl1.getText())) {
                    vendas.remove(i);
                    vendaProdutos.remove(i);
                }
            }

            //esvazia o arraylist dadosPessoa e, conseguentemente, esvazia a jTable.
            LimparTabela2();
            //preenche a jTable com os dados restantes do arraylist pessoas.
            for (int i = 0; i < vendas.size(); i++) {
                preencherTabela2(vendas.get(i).getA(), vendas.get(i).getB(), vendas.get(i).getC(), vendas.get(i).getD(), vendas.get(i).getE(),
                        vendas.get(i).getF(), vendas.get(i).getG(), vendas.get(i).getH(), vendas.get(i).getJ());
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable29MouseClicked
        int linhaSelecionada = jTable29.getSelectedRow();
        lbl1.setText(jTable29.getValueAt(linhaSelecionada, 0).toString());
        lbl2.setText(jTable29.getValueAt(linhaSelecionada, 1).toString());
        lbl3.setText(jTable29.getValueAt(linhaSelecionada, 2).toString());
        lbl4.setText(jTable29.getValueAt(linhaSelecionada, 3).toString());
        lbl5.setText(jTable29.getValueAt(linhaSelecionada, 4).toString());
        lbl6.setText(jTable29.getValueAt(linhaSelecionada, 5).toString());
        lbl7.setText(jTable29.getValueAt(linhaSelecionada, 6).toString());
        lbl8.setText(jTable29.getValueAt(linhaSelecionada, 7).toString());
        lbl9.setText(jTable29.getValueAt(linhaSelecionada, 8).toString());
    }//GEN-LAST:event_jTable29MouseClicked

    // <editor-fold defaultstate="collapsed" desc="preencher tabela 1">
    public void preencherTabela(String SQL) {
        DAO dao = new DAO();
        vendaProdutosController vd = new vendaProdutosController();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Descrição", "Valor Unitário", "QTD", "Desconto", "Valor",
            "DescontoVenda", "TipoPagamento", "Icms", "Iss", "Ipi", "Data", "Observacao", "FKfuncionario", "codigoVenda", "codigoFuncionario"};

        String[] colunas2 = new String[]{"Produto", "Valor Unitário", "Quantidade", "Desconto", "Valor", "Icms", "ISS", "IPI", "idLote"};

        dao.executaSQL(SQL);
        try {
            dao.resultSet.first();
            do {
                double qq = Double.parseDouble(dao.resultSet.getString("valorParcial"));
                double qr = qq * (-1);

                dadosVendas.add(new Object[]{dao.resultSet.getString("nomeProduto"), dao.resultSet.getString("valorVenda"),
                    dao.resultSet.getString("qtd"), dao.resultSet.getString("descontos"), dao.resultSet.getString("valorParcial"),
                    dao.resultSet.getString("icms"), dao.resultSet.getString("iss"), dao.resultSet.getString("ipi"),
                    dao.resultSet.getString("FKlote")});

                vendas.add(vd.preencherArray3(dao.resultSet.getString("nomeProduto"), dao.resultSet.getString("valorVenda"), dao.resultSet.getString("qtd"), dao.resultSet.getString("descontos"),
                        dao.resultSet.getString("valorParcial"), dao.resultSet.getString("icms"), dao.resultSet.getString("iss"), dao.resultSet.getString("ipi"), dao.resultSet.getString("FKlote")));

                vendaProdutos.add(vd.preencherCarrinho(dao.resultSet.getString("FKlote"), dao.resultSet.getString("qtd"), dao.resultSet.getString("descontos"),
                        dao.resultSet.getString("valorParcial"), dao.resultSet.getString("codigoVenda")));

                vendaProdutos2.add(vd.preencherCarrinho(dao.resultSet.getString("FKlote"), dao.resultSet.getString("qtd"), dao.resultSet.getString("descontos"),
                        Double.toString(qr), dao.resultSet.getString("codigoVenda")));

                dados.add(new Object[]{dao.resultSet.getString("nomeProduto"), dao.resultSet.getString("descricao"), dao.resultSet.getString("valorVenda"),
                    dao.resultSet.getString("qtd"), dao.resultSet.getString("descontos"), Double.toString(qr),
                    dao.resultSet.getString("desconto"), dao.resultSet.getString("tipoPagamento"), dao.resultSet.getString("icms"), dao.resultSet.getString("iss"),
                    dao.resultSet.getString("ipi"), dao.resultSet.getString("dataVenda"), dao.resultSet.getString("observacao"),
                    dao.resultSet.getString("FKfuncionario"), dao.resultSet.getString("codigoVenda"), dao.resultSet.getString("codigoFuncionario")});

                x = Double.parseDouble(dao.resultSet.getString("valorParcial"));
                z += x;
                vl2 = Double.parseDouble(dao.resultSet.getString("desconto"));
                vl = z - (z * vl2 / 100);
                icms = Double.parseDouble(dao.resultSet.getString("icms"));
                icms1 += icms;
                iss1 = Double.parseDouble(dao.resultSet.getString("iss"));
                iss2 += iss1;
                ipi1 = Double.parseDouble(dao.resultSet.getString("ipi"));
                ipi2 += ipi1;

                lblValor.setText(Double.toString(z));
                lblValorTotal.setText(Double.toString(vl * (-1)));
                lblIcms.setText(Double.toString(icms1));
                lblIss.setText(Double.toString(iss2));
                lblIpi.setText(Double.toString(ipi2));
                lblDataVenda.setText(dao.resultSet.getString("dataVenda"));
                lblDescontoGeral.setText(dao.resultSet.getString("desconto"));
                lblCodfuncionario.setText(dao.resultSet.getString("codigoFuncionario"));
                lblCodvenda.setText(dao.resultSet.getString("codigoVenda"));
                lblFKfuncionario.setText(dao.resultSet.getString("FKfuncionario"));
                lbltipoPag.setText(dao.resultSet.getString("tipoPagamento"));

            } while (dao.resultSet.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Ñ DEU");
        }

        ModeloTabela model = new ModeloTabela(dados, colunas);
        jTable2.setModel(model);

        jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(6).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(7).setResizable(false);
        jTable2.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(8).setResizable(false);
        jTable2.getColumnModel().getColumn(9).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(9).setResizable(false);
        jTable2.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTable2.getColumnModel().getColumn(10).setResizable(false);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(11).setResizable(false);
        jTable2.getColumnModel().getColumn(12).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable2.getColumnModel().getColumn(12).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable2.getColumnModel().getColumn(13).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(13).setResizable(false);
        jTable2.getColumnModel().getColumn(14).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(14).setResizable(false);
        jTable2.getColumnModel().getColumn(15).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(15).setResizable(false);

        jTable2.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela

        TabelaModelo2 models = new TabelaModelo2(dadosVendas, colunas2);
        jTable29.setModel(models);

        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(1).setResizable(false);
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela

    }

    //</editor-fold>
//(String produto, String qtd, String desconto, String vlUnitario, String vlParcial, String icms, String iss, String ipi, String idLote)
  
    // <editor-fold defaultstate="collapsed" desc="preencher tabela 2">   
    public void preencherTabela2(String produto, String vlUnitario, String qtd, String desconto, String vlParcial, String icmsx, String issx, String ipix, String idLote) {
        //Calcular valores
        //calcular impostos
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date agr = new Date();
        
        String[] colunas = new String[]{"Produto", "Valor Unitário", "Quantidade", "Desconto", "Valor", "icsm", "iss", "ipi", "idLote"};
        try {
            dadosVendas2.add(new Object[]{produto, vlUnitario, qtd, desconto, vlParcial, icmsx, issx, ipix, idLote});

            x22 = Double.parseDouble(vlParcial);
            z22 += x22;
            vl222 = Double.parseDouble(desconto);
            z22 = z22 - (z22 * vl222 / 100);
            icms122 = Double.parseDouble(icmsx);
            icms22 += icms122;
            iss122 = Double.parseDouble(issx);
            iss222 += iss122;
            ipi122 = Double.parseDouble(ipix);
            ipi222 += ipi122;

            lblImposto1.setText(Double.toString(icms22));
            lblImposto2.setText(Double.toString(iss222));
            lblImposto3.setText(Double.toString(ipi222));
            lblValorTotalx.setText(Double.toString(z22));
            lblDescontoGeralx.setText(Double.toString(vl222));
            lblDataVendax.setText(df.format(agr));
            lblCodfuncionario1.setText(lblCodfuncionario.getText());
            lblFKfuncionario1.setText(lblFKfuncionario.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        TabelaModelo2 model = new TabelaModelo2(dadosVendas2, colunas);
        jTable29.setModel(model);

        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(0).setResizable(true);  // não permite alterar o tamanho da coluna
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(1).setResizable(false);
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="preencher tabela 2">

    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Tipo Pagamento">
    public void tipoPagamento() {
        if (cbD.isSelected()) {
            tp = "1";
            //  txtDinheiro.setEnabled(true);
            //  txtTroco.setEnabled(true);
            // txtCartao.setEnabled(false);
        } else {
            tp = "0";
            // txtDinheiro.setEnabled(false);
            // txtTroco.setEnabled(false);
            // txtCartao.setEnabled(false);
        }
        if (cbCC.isSelected()) {
            tp = "2";
            // txtDinheiro.setEnabled(false);
            // txtTroco.setEnabled(false);
            // txtCartao.setEnabled(false);
        }
        if (cbCD.isSelected()) {
            tp = "3";
            // txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            // txtCartao.setEnabled(false);
        }
        if (cbD.isSelected() && cbCC.isSelected() || cbD.isSelected() && cbCD.isSelected()) {
            tp = "1";
            // txtDinheiro.setEnabled(true);
            //  txtTroco.setEnabled(true);
            // txtCartao.setEnabled(true);
        }
        if (cbD.isSelected() && cbCC.isSelected() && cbCD.isSelected()) {
            JOptionPane.showMessageDialog(null, "Opção inválida");
            //   cbD.setSelected(false);
            // cbCC.setSelected(false);
            // cbCD.setSelected(false);
            // txtDinheiro.setEnabled(false);
            //  txtTroco.setEnabled(false);
            //  txtCartao.setEnabled(false);
        }

    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Limpar tabela 2">
    public void LimparTabela2() {
        String[] colunas = new String[]{"Produto", "Valor Unitário", "Quantidade", "Desconto", "Valor", "icsm", "iss", "ipi", "idLote"};

        dadosVendas2.removeAll(dadosVendas2);
        //evazia a jTable, add dadosPessoa (sem dados).
        ModeloTabela modelo = new ModeloTabela(dadosVendas2, colunas);
        jTable29.setModel(modelo); // recebe o modelo criado
        jTable29.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable29.getColumnModel().getColumn(0).setResizable(false);
        jTable29.getColumnModel().getColumn(1).setPreferredWidth(150);  // define o tamanho das colunas e se será redimensionado ou não
        jTable29.getColumnModel().getColumn(1).setResizable(true);  // não permite alterar o tamanho da coluna 
        jTable29.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(2).setResizable(false);
        jTable29.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(3).setResizable(false);
        jTable29.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable29.getColumnModel().getColumn(4).setResizable(false);
        jTable29.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(5).setResizable(false);
        jTable29.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(6).setResizable(false);
        jTable29.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(7).setResizable(false);
        jTable29.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable29.getColumnModel().getColumn(8).setResizable(false);

        jTable29.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTable29.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTable29.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="JAVA - do not modify"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEstorno;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JCheckBox cbCC;
    private javax.swing.JCheckBox cbCC1;
    private javax.swing.JCheckBox cbCD;
    private javax.swing.JCheckBox cbCD1;
    private javax.swing.JCheckBox cbD;
    private javax.swing.JCheckBox cbD1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable29;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblCodfuncionario;
    private javax.swing.JLabel lblCodfuncionario1;
    private javax.swing.JLabel lblCodigoFunc;
    private javax.swing.JLabel lblCodigoFunc1;
    private javax.swing.JLabel lblCodvenda;
    private javax.swing.JLabel lblCodvenda1;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblDataVendax;
    private javax.swing.JLabel lblDescontoGeral;
    private javax.swing.JLabel lblDescontoGeralx;
    private javax.swing.JLabel lblFKfuncionario;
    private javax.swing.JLabel lblFKfuncionario1;
    private javax.swing.JLabel lblIcms;
    private javax.swing.JLabel lblImposto1;
    private javax.swing.JLabel lblImposto2;
    private javax.swing.JLabel lblImposto3;
    private javax.swing.JLabel lblIpi;
    private javax.swing.JLabel lblIss;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorParcialx;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotalx;
    private javax.swing.JLabel lblestorno;
    private javax.swing.JLabel lblestorno1;
    private javax.swing.JLabel lbltipoPag;
    private javax.swing.JLabel lbltipoPag1;
    private javax.swing.JTextField txtCodVenda;
    private javax.swing.JTextArea txtObservacao;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
